#! /usr/bin/env python3

'''
The main entry for all tasks.
'''

import argparse

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description="Main entry for multiple functions.")

    subparsers = parser.add_subparsers(dest="command", required=True)

    from tasks import task_wsserver
    task_wsserver.build_parser(subparsers)
    # ./main wsserver

    from tasks import task_wsclient
    task_wsclient.build_parser(subparsers)
    # ./main wsclient

    from tasks import task_cli
    task_cli.build_parser(subparsers)
    # ./main cli --mode=loop

    from tasks import task_mic_server
    task_mic_server.build_parser(subparsers)
    # ./main mic_server --format=Int32 --sr=48000 --ch=1

    from tasks import task_speaker_client
    task_speaker_client.build_parser(subparsers)
    # ./main speaker_client --format=Int32 --sr=48000 --ch=1

    from tasks import task_wavfile_server
    task_wavfile_server.build_parser(subparsers)
    # ./main wavfile_server --path=resources/record.wav --format=Float32 --sr=48000 --ch=1
    
    from tasks import task_wavfile_client
    task_wavfile_client.build_parser(subparsers)
    # ./main wavfile_client --path=resources/output.wav --format=Float32 --sr=48000 --ch=1

    # Parse arguments
    args = parser.parse_args()
    
    # Call the function associated with the chosen command
    args.func(args)